-- Excluir tabelas dependentes primeiro
DROP TABLE posicao CASCADE CONSTRAINTS;
DROP TABLE sensor CASCADE CONSTRAINTS;
DROP TABLE manutencao CASCADE CONSTRAINTS;
DROP TABLE moto CASCADE CONSTRAINTS;

-- Depois as tabelas independentes
DROP TABLE patio CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;



-- Criar tabela Pátio
CREATE TABLE patio (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    endereco VARCHAR2(255) NOT NULL,
    capacidade NUMBER NOT NULL
);

-- Criar tabela Moto
CREATE TABLE moto (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR2(10) NOT NULL UNIQUE,
    modelo VARCHAR2(50) NOT NULL,
    status VARCHAR2(20) CHECK (status IN ('DISPONIVEL', 'EM_USO', 'MANUTENCAO', 'INATIVA')),
    patio_id NUMBER,
    ultima_atualizacao TIMESTAMP,
    FOREIGN KEY (patio_id) REFERENCES patio(id)
);

-- Criar tabela Posicao
CREATE TABLE posicao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moto_id NUMBER,
    latitude NUMBER NOT NULL,
    longitude NUMBER NOT NULL,
    timestamp TIMESTAMP,
    FOREIGN KEY (moto_id) REFERENCES moto(id)
);

-- Criar tabela Sensor
CREATE TABLE sensor (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moto_id NUMBER UNIQUE,
    ligado NUMBER(1),
    nivel_bateria NUMBER,
    nivel_combustivel NUMBER,
    ultima_atualizacao TIMESTAMP,
    FOREIGN KEY (moto_id) REFERENCES moto(id)
);

CREATE TABLE manutencao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moto_id NUMBER NOT NULL,
    descricao VARCHAR2(255),
    custo NUMBER(10,2),
    data_manutencao DATE,
    FOREIGN KEY (moto_id) REFERENCES moto(id)
);

CREATE TABLE usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    tipo_usuario VARCHAR2(20) CHECK (tipo_usuario IN ('ADMIN', 'OPERADOR', 'TÉCNICO'))
);


-- Tabela patio
INSERT INTO patio (nome, endereco, capacidade) VALUES ('Pátio Central', 'Av. Paulista, 1000', 50);
INSERT INTO patio (nome, endereco, capacidade) VALUES ('Pátio Norte', 'Rua das Flores, 200', 30);
INSERT INTO patio (nome, endereco, capacidade) VALUES ('Pátio Sul', 'Av. Atlântica, 150', 40);
INSERT INTO patio (nome, endereco, capacidade) VALUES ('Pátio Leste', 'Rua Limoeiro, 500', 25);
INSERT INTO patio (nome, endereco, capacidade) VALUES ('Pátio Oeste', 'Av. dos Bandeirantes, 300', 60);

-- Tabela moto
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('ABC1234', 'Honda CG 160', 'DISPONIVEL', 1, SYSDATE);
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('XYZ5678', 'Yamaha Factor', 'EM_USO', 2, SYSDATE);
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('DEF4321', 'Honda Biz', 'MANUTENCAO', 3, SYSDATE);
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('GHI8765', 'Suzuki Burgman', 'DISPONIVEL', 4, SYSDATE);
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('JKL1357', 'Shineray Jet', 'INATIVA', 5, SYSDATE);

-- Tabela posicao
INSERT INTO posicao (moto_id, latitude, longitude, timestamp) VALUES (1, -23.5611, -46.6555, SYSDATE);
INSERT INTO posicao (moto_id, latitude, longitude, timestamp) VALUES (2, -23.5633, -46.6577, SYSDATE);
INSERT INTO posicao (moto_id, latitude, longitude, timestamp) VALUES (3, -23.5644, -46.6588, SYSDATE);
INSERT INTO posicao (moto_id, latitude, longitude, timestamp) VALUES (4, -23.5655, -46.6599, SYSDATE);
INSERT INTO posicao (moto_id, latitude, longitude, timestamp) VALUES (5, -23.5666, -46.6611, SYSDATE);

-- Tabela sensor
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (1, 1, 90, 70, SYSDATE);
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (2, 1, 75, 60, SYSDATE);
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (3, 0, 40, 20, SYSDATE);
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (4, 1, 85, 50, SYSDATE);
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (5, 0, 30, 15, SYSDATE);

-- Tabela manutencao
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (1, 'Troca de óleo', 50.00, SYSDATE - 10);
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (2, 'Revisão completa', 200.00, SYSDATE - 20);
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (3, 'Troca de pneus', 300.00, SYSDATE - 5);
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (4, 'Alinhamento', 80.00, SYSDATE - 15);
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (5, 'Troca de bateria', 150.00, SYSDATE - 30);

-- Tabela usuario
INSERT INTO usuario (nome, email, tipo_usuario) VALUES ('Carlos Souza', 'carlos@mottu.com', 'ADMIN');
INSERT INTO usuario (nome, email, tipo_usuario) VALUES ('Ana Oliveira', 'ana@mottu.com', 'OPERADOR');
INSERT INTO usuario (nome, email, tipo_usuario) VALUES ('Lucas Lima', 'lucas@mottu.com', 'TÉCNICO');
INSERT INTO usuario (nome, email, tipo_usuario) VALUES ('Juliana Costa', 'juliana@mottu.com', 'OPERADOR');
INSERT INTO usuario (nome, email, tipo_usuario) VALUES ('Bruno Martins', 'bruno@mottu.com', 'TÉCNICO');


-- Bloco de anônimos PL/SQL 
-- Consulta 1
SET SERVEROUTPUT ON;
BEGIN
  FOR registro_patio IN (
    SELECT patio_info.nome AS nome_patio, COUNT(moto_data.id) AS total_motos
    FROM patio patio_info
    LEFT JOIN moto moto_data ON moto_data.patio_id = patio_info.id
    GROUP BY patio_info.nome
    ORDER BY total_motos DESC
  ) LOOP
    DBMS_OUTPUT.PUT_LINE('Pátio: ' || registro_patio.nome_patio || ' - Total de Motos: ' || registro_patio.total_motos);
  END LOOP;
END;

-- Consulta 2
SET SERVEROUTPUT ON;
BEGIN
  FOR combustivel_patio IN (
    SELECT patio_info.nome AS nome_patio, ROUND(AVG(sensor_info.nivel_combustivel), 2) AS media_combustivel
    FROM patio patio_info
    JOIN moto moto_data ON moto_data.patio_id = patio_info.id
    JOIN sensor sensor_info ON sensor_info.moto_id = moto_data.id
    GROUP BY patio_info.nome
    ORDER BY media_combustivel DESC
  ) LOOP
    DBMS_OUTPUT.PUT_LINE('Pátio: ' || combustivel_patio.nome_patio || ' - Média de Combustível: ' || combustivel_patio.media_combustivel || '%');
  END LOOP;
END;

-- Consulta 3
SET SERVEROUTPUT ON;
BEGIN
  FOR status_registro IN (
    SELECT moto_data.status AS status_moto, COUNT(*) AS quantidade
    FROM moto moto_data
    GROUP BY moto_data.status
    ORDER BY quantidade DESC
  ) LOOP
    DBMS_OUTPUT.PUT_LINE('Status: ' || status_registro.status_moto || ' - Quantidade de Motos: ' || status_registro.quantidade);
  END LOOP;
END;


-- Linha anterior, atual, proxima
SET SERVEROUTPUT ON;
DECLARE
  TYPE tipo_moto IS TABLE OF moto.placa%TYPE INDEX BY PLS_INTEGER;
  vetor_motos tipo_moto;
  total_motos NUMBER;
BEGIN
  -- Buscar todas as placas ordenadas
  SELECT placa
  BULK COLLECT INTO vetor_motos
  FROM moto
  ORDER BY id;

  -- Descobrir o total de motos coletadas
  total_motos := vetor_motos.COUNT;

  -- Percorrer o vetor
  FOR i IN 1..total_motos LOOP
    -- Mostrar a placa anterior
    IF i = 1 THEN
      DBMS_OUTPUT.PUT_LINE('Anterior: Vazio');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Anterior: ' || vetor_motos(i - 1));
    END IF;

    -- Mostrar a placa atual
    DBMS_OUTPUT.PUT_LINE('Atual: ' || vetor_motos(i));

    -- Mostrar a placa próxima
    IF i = total_motos THEN
      DBMS_OUTPUT.PUT_LINE('Próxima: Vazio');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Próxima: ' || vetor_motos(i + 1));
    END IF;

    DBMS_OUTPUT.PUT_LINE('---------------------------');
  END LOOP;
END;


-- Total de aluguel por clientes
SET SERVEROUTPUT ON;
BEGIN
   FOR r IN (
      SELECT m.placa AS placa_moto,
             COUNT(mt.id) AS total_manutencoes
      FROM moto m
      JOIN manutencao mt ON m.id = mt.moto_id
      GROUP BY m.placa
      ORDER BY total_manutencoes DESC
   ) LOOP
      DBMS_OUTPUT.PUT_LINE('Placa: ' || r.placa_moto || ' - Total de Manutenções: ' || r.total_manutencoes);
   END LOOP;
END;

-- Media do combustivel por media das motos
SET SERVEROUTPUT ON;
BEGIN
   FOR r IN (
      SELECT m.placa,
             m.status,
             ROUND(s.nivel_combustivel, 2) AS media_combustivel
      FROM moto m
      JOIN sensor s ON m.id = s.moto_id
      ORDER BY m.status, s.nivel_combustivel DESC
   ) LOOP
      DBMS_OUTPUT.PUT_LINE('Status moto ' || r.placa || ': ' || r.status || ' - Nível de Combustível: ' || r.media_combustivel);
   END LOOP;
END;

-- Quantidade de motos no patio
SET SERVEROUTPUT ON;
BEGIN
   FOR r IN (
      SELECT p.nome AS nome_patio,
             COUNT(m.id) AS total_motos
      FROM patio p
      JOIN moto m ON p.id = m.patio_id
      GROUP BY p.nome
      ORDER BY total_motos DESC
   ) LOOP
      DBMS_OUTPUT.PUT_LINE('Pátio: ' || r.nome_patio || ' - Total de Motos: ' || r.total_motos);
   END LOOP;
END;


