-- ========================================================================
-- Participantes
-- Luiz Felipe Abreu - RM555197
-- Matheus Munuera – RM557812
-- Pedro Gomes - RM553907

-- ========================================================================

-- ========================================================================
-- EXCLUSÃO DAS TABELAS NA ORDEM CORRETA
-- ========================================================================
DROP TRIGGER trg_auditoria_moto;
DROP TABLE auditoria_moto CASCADE CONSTRAINTS;
DROP TABLE movimentacao CASCADE CONSTRAINTS;
DROP TABLE posicao CASCADE CONSTRAINTS;
DROP TABLE sensor CASCADE CONSTRAINTS;
DROP TABLE manutencao CASCADE CONSTRAINTS;
DROP TABLE moto CASCADE CONSTRAINTS;
DROP TABLE patio CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;

-- ========================================================================
-- CRIAÇÃO DAS TABELAS PRINCIPAIS
-- ========================================================================

-- Pátio
CREATE TABLE patio (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100) NOT NULL,
  endereco VARCHAR2(255) NOT NULL,
  capacidade NUMBER NOT NULL,
  classe VARCHAR2(20) CHECK (classe IN ('POP', 'SPORT', 'ELETRICA'))
);

-- Motos
CREATE TABLE moto (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  placa VARCHAR2(10) NOT NULL UNIQUE,
  modelo VARCHAR2(50) NOT NULL,
  status VARCHAR2(20) CHECK (status IN ('DISPONIVEL', 'EM_USO', 'MANUTENCAO', 'INATIVA')),
  patio_id NUMBER,
  ultima_atualizacao TIMESTAMP,
  FOREIGN KEY (patio_id) REFERENCES patio(id)
);

-- Posições (CORRIGIDO: timestamp → dt_posicao para evitar conflitos)
CREATE TABLE posicao (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moto_id NUMBER,
  latitude NUMBER NOT NULL,
  longitude NUMBER NOT NULL,
  dt_posicao TIMESTAMP,
  FOREIGN KEY (moto_id) REFERENCES moto(id)
);

-- Movimentações (CORRIGIDO: timestamp → dt_evento para consistência)
CREATE TABLE movimentacao (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moto_id NUMBER NOT NULL,
  tipo_evento VARCHAR2(20) CHECK (tipo_evento IN ('ENTRADA', 'SAIDA', 'MOVIMENTACAO')),
  descricao VARCHAR2(255),
  dt_evento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (moto_id) REFERENCES moto(id)
);

-- Sensores
CREATE TABLE sensor (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moto_id NUMBER UNIQUE,
  ligado NUMBER(1),
  nivel_bateria NUMBER,
  nivel_combustivel NUMBER,
  ultima_atualizacao TIMESTAMP,
  FOREIGN KEY (moto_id) REFERENCES moto(id)
);

-- Manutenção
CREATE TABLE manutencao (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moto_id NUMBER NOT NULL,
  descricao VARCHAR2(255),
  custo NUMBER(10,2),
  data_manutencao DATE,
  FOREIGN KEY (moto_id) REFERENCES moto(id)
);

-- Usuários
CREATE TABLE usuario (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100) NOT NULL,
  email VARCHAR2(100) NOT NULL UNIQUE,
  forma_pagamento VARCHAR2(20) CHECK (forma_pagamento IN ('PIX', 'CREDITO', 'BOLETO')),
  idade NUMBER NOT NULL
);

-- ========================================================================
-- INSERÇÃO DE DADOS DE EXEMPLO
-- ========================================================================

-- Pátios
INSERT INTO patio (nome, endereco, capacidade, classe) VALUES ('Pátio Central', 'Av. Paulista, 1000', 50, 'POP');
INSERT INTO patio (nome, endereco, capacidade, classe) VALUES ('Pátio Norte', 'Rua das Flores, 200', 30, 'SPORT');
INSERT INTO patio (nome, endereco, capacidade, classe) VALUES ('Pátio Sul', 'Av. Atlântica, 150', 40, 'ELETRICA');
INSERT INTO patio (nome, endereco, capacidade, classe) VALUES ('Pátio Leste', 'Rua Limoeiro, 500', 25, 'POP');
INSERT INTO patio (nome, endereco, capacidade, classe) VALUES ('Pátio Oeste', 'Av. dos Bandeirantes, 300', 60, 'SPORT');

-- Motos
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('ABC1234', 'Mottu Pop', 'DISPONIVEL', 1, SYSDATE);
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('XYZ5678', 'Mottu Sport', 'EM_USO', 2, SYSDATE);
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('DEF4321', 'Mottu-E', 'MANUTENCAO', 3, SYSDATE);
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('GHI8765', 'Mottu Pop', 'DISPONIVEL', 4, SYSDATE);
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao) VALUES ('JKL1357', 'Mottu Sport', 'INATIVA', 5, SYSDATE);

-- Posições (CORRIGIDO: timestamp → dt_posicao)
INSERT INTO posicao (moto_id, latitude, longitude, dt_posicao) VALUES (1, -23.5611, -46.6555, SYSDATE);
INSERT INTO posicao (moto_id, latitude, longitude, dt_posicao) VALUES (2, -23.5633, -46.6577, SYSDATE);
INSERT INTO posicao (moto_id, latitude, longitude, dt_posicao) VALUES (3, -23.5644, -46.6588, SYSDATE);
INSERT INTO posicao (moto_id, latitude, longitude, dt_posicao) VALUES (4, -23.5655, -46.6599, SYSDATE);
INSERT INTO posicao (moto_id, latitude, longitude, dt_posicao) VALUES (5, -23.5666, -46.6611, SYSDATE);

-- Movimentações
INSERT INTO movimentacao (moto_id, tipo_evento, descricao) VALUES (1, 'ENTRADA', 'Moto entrou no pátio pela cancela principal');
INSERT INTO movimentacao (moto_id, tipo_evento, descricao) VALUES (1, 'MOVIMENTACAO', 'Moto deslocada para área de manutenção');
INSERT INTO movimentacao (moto_id, tipo_evento, descricao) VALUES (1, 'SAIDA', 'Moto saiu do pátio pela cancela principal');
INSERT INTO movimentacao (moto_id, tipo_evento, descricao) VALUES (2, 'ENTRADA', 'Moto devolvida após uso externo');
INSERT INTO movimentacao (moto_id, tipo_evento, descricao) VALUES (2, 'MOVIMENTACAO', 'Moto alocada para área de lavagem');

-- Sensores
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (1, 1, 90, 70, SYSDATE);
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (2, 1, 75, 60, SYSDATE);
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (3, 0, 40, 20, SYSDATE);
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (4, 1, 85, 50, SYSDATE);
INSERT INTO sensor (moto_id, ligado, nivel_bateria, nivel_combustivel, ultima_atualizacao) VALUES (5, 0, 30, 15, SYSDATE);

-- Manutenções
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (1, 'Troca de óleo', 50.00, SYSDATE - 10);
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (2, 'Revisão completa', 200.00, SYSDATE - 20);
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (3, 'Troca de pneus', 300.00, SYSDATE - 5);
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (4, 'Alinhamento e balanceamento', 80.00, SYSDATE - 15);
INSERT INTO manutencao (moto_id, descricao, custo, data_manutencao) VALUES (5, 'Troca de bateria', 150.00, SYSDATE - 30);

-- Usuários
INSERT INTO usuario (nome, email, forma_pagamento, idade) VALUES ('Carlos Souza', 'carlos@mottu.com', 'PIX', 38);
INSERT INTO usuario (nome, email, forma_pagamento, idade) VALUES ('Ana Oliveira', 'ana@mottu.com', 'CREDITO', 29);
INSERT INTO usuario (nome, email, forma_pagamento, idade) VALUES ('Lucas Lima', 'lucas@mottu.com', 'BOLETO', 34);
INSERT INTO usuario (nome, email, forma_pagamento, idade) VALUES ('Juliana Costa', 'juliana@mottu.com', 'PIX', 27);
INSERT INTO usuario (nome, email, forma_pagamento, idade) VALUES ('Bruno Martins', 'bruno@mottu.com', 'CREDITO', 31);
INSERT INTO usuario (nome, email, forma_pagamento, idade) VALUES ('Fernanda Ribeiro', 'fernanda@mottu.com', 'BOLETO', 41);

-- ========================================================================
-- FUNÇÃO 1: GERAR JSON DETALHADO DE UMA MOTO (CORRIGIDA)
-- ========================================================================
CREATE OR REPLACE FUNCTION fn_gerar_json_detalhes_moto(p_id_moto IN NUMBER)
RETURN CLOB IS
  v_json_resultado CLOB := '{';
  v_placa_moto moto.placa%TYPE;
  v_modelo_moto moto.modelo%TYPE;
  v_status_moto moto.status%TYPE;
  v_nome_patio patio.nome%TYPE;
  v_ultima_latitude_moto posicao.latitude%TYPE;
  v_ultima_longitude_moto posicao.longitude%TYPE;
  v_ultimo_tipo_evento_moto movimentacao.tipo_evento%TYPE;
  v_ultima_data_evento_moto movimentacao.dt_evento%TYPE;

  -- util para escapar aspas em strings JSON
  FUNCTION esc(p VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF p IS NULL THEN RETURN NULL; END IF;
    RETURN REPLACE(p,'"','\"');
  END;
BEGIN
  -- Dados principais da moto + pátio
  SELECT m.placa, m.modelo, m.status, p.nome
  INTO v_placa_moto, v_modelo_moto, v_status_moto, v_nome_patio
  FROM moto m
  JOIN patio p ON p.id = m.patio_id
  WHERE m.id = p_id_moto;

  -- Última posição (se existir)
  BEGIN
    SELECT latitude, longitude
    INTO v_ultima_latitude_moto, v_ultima_longitude_moto
    FROM posicao
    WHERE moto_id = p_id_moto
      AND dt_posicao = (
        SELECT MAX(dt_posicao) FROM posicao WHERE moto_id = p_id_moto
      );
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      v_ultima_latitude_moto := NULL;
      v_ultima_longitude_moto := NULL;
  END;

  -- Última movimentação (se existir)
  BEGIN
    SELECT tipo_evento, dt_evento
    INTO v_ultimo_tipo_evento_moto, v_ultima_data_evento_moto
    FROM movimentacao
    WHERE moto_id = p_id_moto
      AND dt_evento = (SELECT MAX(dt_evento) FROM movimentacao WHERE moto_id = p_id_moto);
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      v_ultimo_tipo_evento_moto := NULL;
      v_ultima_data_evento_moto := NULL;
  END;

  -- Montagem manual do JSON (valores NULL retornam null JSON sem aspas)
  v_json_resultado := v_json_resultado
    || '"id_moto": ' || p_id_moto || ', '
    || '"placa": "'  || esc(v_placa_moto) || '", '
    || '"modelo": "' || esc(v_modelo_moto) || '", '
    || '"status": "' || esc(v_status_moto) || '", '
    || '"nome_patio": "' || esc(v_nome_patio) || '", '
    || '"latitude": ' || NVL(TO_CHAR(v_ultima_latitude_moto),'null') || ', '
    || '"longitude": ' || NVL(TO_CHAR(v_ultima_longitude_moto),'null') || ', '
    || '"ultimo_evento": ' ||
         CASE WHEN v_ultimo_tipo_evento_moto IS NULL
              THEN 'null'
              ELSE '"'||esc(v_ultimo_tipo_evento_moto)||'"' END || ', '
    || '"data_ultimo_evento": ' ||
         CASE WHEN v_ultima_data_evento_moto IS NULL
              THEN 'null'
              ELSE '"'||TO_CHAR(v_ultima_data_evento_moto,'YYYY-MM-DD HH24:MI:SS')||'"' END
    || '}';

  RETURN v_json_resultado;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN '{"erro": "Moto não encontrada"}';
  WHEN TOO_MANY_ROWS THEN
    RETURN '{"erro": "Inconsistência: múltiplas linhas para a moto '||p_id_moto||'"}';
  WHEN VALUE_ERROR THEN
    RETURN '{"erro": "Erro de conversão/concatenação (VALUE_ERROR)"}';
  WHEN OTHERS THEN
    RETURN '{"erro": "Erro inesperado: ' || REPLACE(SQLERRM,'"','\"') || '"}';
END fn_gerar_json_detalhes_moto;

-- ========================================================================
-- FUNÇÃO 2: CALCULAR PERCENTUAL DE OCUPAÇÃO DE UM PÁTIO (MELHORADA)
-- ========================================================================
CREATE OR REPLACE FUNCTION fn_calcular_percentual_ocupacao_patio(p_id_patio IN NUMBER)
RETURN VARCHAR2 IS
  v_qtd_motos NUMBER;
  v_capacidade NUMBER;
  v_percentual NUMBER(5,2);
  v_msg VARCHAR2(200);
  ex_capacidade_zero EXCEPTION;
BEGIN
  -- Busca capacidade do pátio
  SELECT capacidade INTO v_capacidade FROM patio WHERE id = p_id_patio;

  -- Verifica se a capacidade é zero
  IF v_capacidade = 0 THEN
    RAISE ex_capacidade_zero;
  END IF;

  -- Conta motos ativas
  SELECT COUNT(*) INTO v_qtd_motos
  FROM moto
  WHERE patio_id = p_id_patio
    AND status IN ('DISPONIVEL','EM_USO','MANUTENCAO');

  -- Calcula percentual
  v_percentual := (v_qtd_motos / v_capacidade) * 100;
  v_msg := 'O pátio '||p_id_patio||' está com '||TO_CHAR(v_percentual,'90.99')||'% de ocupação.';

  RETURN v_msg;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 'Erro: Pátio '||p_id_patio||' não encontrado.';
  WHEN ex_capacidade_zero THEN
    RETURN 'Erro: Capacidade do pátio '||p_id_patio||' não pode ser zero.';
  WHEN ZERO_DIVIDE THEN
    RETURN 'Erro: División por zero no pátio '||p_id_patio||'.';
  WHEN VALUE_ERROR THEN
    RETURN 'Erro: Valor inválido no cálculo para pátio '||p_id_patio||'.';
  WHEN OTHERS THEN
    RETURN 'Erro inesperado: '||SQLERRM;
END fn_calcular_percentual_ocupacao_patio;

-- ========================================================================
-- PROCEDURE 1: GERAR JSON DE TODAS AS MOTOS (MELHORADA)
-- ========================================================================
CREATE OR REPLACE PROCEDURE prc_gerar_json_detalhes_todas_motos IS
  v_json_lista CLOB := '[';
  v_item       CLOB;
  v_count      NUMBER := 0;
  ex_vazio     EXCEPTION;
BEGIN
  -- Faz JOIN entre moto e pátio e chama a função JSON
  FOR r IN (
    SELECT m.id
    FROM moto m
    JOIN patio p ON p.id = m.patio_id
    ORDER BY m.id
  ) LOOP
    v_item := fn_gerar_json_detalhes_moto(r.id);

    IF v_count > 0 THEN
      v_json_lista := v_json_lista || ', ';
    END IF;

    v_json_lista := v_json_lista || v_item;
    v_count := v_count + 1;
  END LOOP;

  IF v_count = 0 THEN
    RAISE ex_vazio;
  END IF;

  v_json_lista := v_json_lista || ']';

  DBMS_OUTPUT.PUT_LINE('JSON COMPLETO DE TODAS AS MOTOS:');
  DBMS_OUTPUT.PUT_LINE(v_json_lista);

EXCEPTION
  WHEN ex_vazio THEN
    DBMS_OUTPUT.PUT_LINE('Nenhuma moto encontrada.');
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Erro: Dados não encontrados.');
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Erro: Muitas linhas retornadas.');
  WHEN VALUE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('Erro: Valor inválido durante processamento.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro inesperado: '||SQLERRM);
END prc_gerar_json_detalhes_todas_motos;

-- ========================================================================
-- PROCEDURE 2: SOMATÓRIO MANUAL DE MANUTENÇÕES POR PÁTIO E MOTO (MELHORADA)
-- ========================================================================
CREATE OR REPLACE PROCEDURE prc_somatorio_manual_motos_por_patio IS
  CURSOR c_dados IS
    SELECT m.patio_id, m.id AS moto_id, NVL(SUM(mt.custo),0) AS valor
    FROM moto m
    LEFT JOIN manutencao mt ON mt.moto_id = m.id
    GROUP BY m.patio_id, m.id
    ORDER BY m.patio_id, m.id;

  v_patio_atual    NUMBER := NULL;
  v_subtotal_patio NUMBER := 0;
  v_total_geral    NUMBER := 0;
  v_tem_dados      BOOLEAN := FALSE;
  ex_sem_dados     EXCEPTION;
  ex_valor_negativo EXCEPTION;
BEGIN
  DBMS_OUTPUT.PUT_LINE('------------------------------------------');
  DBMS_OUTPUT.PUT_LINE(' Patio | Moto | Valor Manutencao');
  DBMS_OUTPUT.PUT_LINE('------------------------------------------');

  FOR r IN c_dados LOOP
    v_tem_dados := TRUE;

    -- Verifica valores negativos
    IF r.valor < 0 THEN
      RAISE ex_valor_negativo;
    END IF;

    -- Quando muda o pátio, imprime subtotal do anterior
    IF v_patio_atual IS NOT NULL AND r.patio_id <> v_patio_atual THEN
      DBMS_OUTPUT.PUT_LINE(' '||v_patio_atual||' | NULL | '||v_subtotal_patio);
      v_subtotal_patio := 0;
    END IF;

    -- Imprime linha da moto
    DBMS_OUTPUT.PUT_LINE(' '||r.patio_id||' | '||r.moto_id||' | '||r.valor);
    
    v_subtotal_patio := v_subtotal_patio + r.valor;
    v_total_geral := v_total_geral + r.valor;
    v_patio_atual := r.patio_id;
  END LOOP;

  IF NOT v_tem_dados THEN
    RAISE ex_sem_dados;
  END IF;

  -- Subtotal do último pátio
  DBMS_OUTPUT.PUT_LINE(' '||v_patio_atual||' | NULL | '||v_subtotal_patio);
  
  -- Total geral
  DBMS_OUTPUT.PUT_LINE('------------------------------------------');
  DBMS_OUTPUT.PUT_LINE(' NULL | NULL | '||v_total_geral);
  DBMS_OUTPUT.PUT_LINE('------------------------------------------');

EXCEPTION
  WHEN ex_sem_dados THEN
    DBMS_OUTPUT.PUT_LINE('Erro: Nenhum registro encontrado.');
  WHEN ex_valor_negativo THEN
    DBMS_OUTPUT.PUT_LINE('Erro: Valor de manutenção negativo encontrado.');
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Erro: Dados não encontrados.');
  WHEN VALUE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('Erro: Erro de conversão de valores.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro inesperado: '||SQLERRM);
END prc_somatorio_manual_motos_por_patio;

-- ========================================================================
-- TRIGGER DE AUDITORIA (MELHORADO)
-- ========================================================================
CREATE TABLE auditoria_moto (
  id_auditoria   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_banco  VARCHAR2(50),
  operacao       VARCHAR2(10),
  data_hora      TIMESTAMP DEFAULT SYSTIMESTAMP,
  valores_antigos CLOB,
  valores_novos   CLOB
);

CREATE OR REPLACE TRIGGER trg_auditoria_moto
AFTER INSERT OR UPDATE OR DELETE ON moto
FOR EACH ROW
BEGIN
  -- INSERT
  IF INSERTING THEN
    INSERT INTO auditoria_moto (usuario_banco, operacao, valores_novos)
    VALUES (USER, 'INSERT',
            'PLACA='||:NEW.placa||', MODELO='||:NEW.modelo||', STATUS='||:NEW.status||', PATIO_ID='||:NEW.patio_id);
  
  -- UPDATE
  ELSIF UPDATING THEN
    INSERT INTO auditoria_moto (usuario_banco, operacao, valores_antigos, valores_novos)
    VALUES (USER, 'UPDATE',
            'PLACA='||:OLD.placa||', MODELO='||:OLD.modelo||', STATUS='||:OLD.status||', PATIO_ID='||:OLD.patio_id,
            'PLACA='||:NEW.placa||', MODELO='||:NEW.modelo||', STATUS='||:NEW.status||', PATIO_ID='||:NEW.patio_id);
  
  -- DELETE
  ELSIF DELETING THEN
    INSERT INTO auditoria_moto (usuario_banco, operacao, valores_antigos)
    VALUES (USER, 'DELETE',
            'PLACA='||:OLD.placa||', MODELO='||:OLD.modelo||', STATUS='||:OLD.status||', PATIO_ID='||:OLD.patio_id);
  END IF;
END trg_auditoria_moto;

-- ========================================================================
-- TESTES DAS FUNÇÕES, PROCEDURES E TRIGGER
-- ========================================================================

-- Teste Função 1: JSON de cada moto
SET SERVEROUTPUT ON;
BEGIN
  FOR r IN (SELECT id FROM moto ORDER BY id) LOOP
    DBMS_OUTPUT.PUT_LINE(fn_gerar_json_detalhes_moto(r.id));
  END LOOP;
END;


-- Teste Função 2: Ocupação de cada pátio
BEGIN
  FOR r IN (SELECT id FROM patio ORDER BY id) LOOP
    DBMS_OUTPUT.PUT_LINE(fn_calcular_percentual_ocupacao_patio(r.id));
  END LOOP;
END;


-- Teste Procedure 1: JSON de todas as motos
BEGIN
  prc_gerar_json_detalhes_todas_motos;
END;


-- Teste Procedure 2: Somatório de manutenções
BEGIN
  prc_somatorio_manual_motos_por_patio;
END;


-- Teste Trigger: INSERÇÃO/UPDATE/DELETE em MOTO
SET SERVEROUTPUT ON;

-- Inserção
INSERT INTO moto (placa, modelo, status, patio_id, ultima_atualizacao)
VALUES ('ZZZ9999', 'TesteMoto', 'DISPONIVEL', 1, SYSTIMESTAMP);
COMMIT;

-- Atualização
UPDATE moto
SET status = 'EM_USO', ultima_atualizacao = SYSTIMESTAMP
WHERE placa = 'ZZZ9999';
COMMIT;

-- Exclusão
DELETE FROM moto WHERE placa = 'ZZZ9999';
COMMIT;

-- Consulta auditoria
SELECT id_auditoria, usuario_banco, operacao, data_hora, valores_antigos, valores_novos
FROM auditoria_moto
ORDER BY id_auditoria;